{% set version = "4.3" %}

package:
  name: pytest-runner
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-runner/pytest-runner-{{ version }}.tar.gz
  sha256: c2353eebc81bc798ae81242e095201de87e2c3b3fcad6130c2aefa39a010f22f

build:
    number: 0
    noarch: python
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0
  run:
    - python
    - setuptools
    - pytest

test:
  imports:
    - ptr

about:
  home: https://github.com/pytest-dev/pytest-runner
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Invoke py.test as distutils command with dependency resolution.'
  dev_url: https://github.com/pytest-dev/pytest-runner

extra:
  recipe-maintainers:
    - dopplershift
    - ocefpaf
