{% set name = "pytest-runner" %}
{% set version = "4.0" %}
{% set sha256 = "183f3745561b1e00ea51cd97634ba5c540848ab4aa8016a81faba7fb7f33ec76" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    noarch: python
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm >=1.15.0

  run:
    - python
    - setuptools
    - pytest

test:
  imports:
    - ptr

about:
  home: https://github.com/pytest-dev/pytest-runner
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Invoke py.test as distutils command with dependency resolution.'
  dev_url: https://github.com/pytest-dev/pytest-runner

extra:
  recipe-maintainers:
    - dopplershift
    - ocefpaf
